apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ai-business-intelligence
  namespace: ai-business-intelligence

resources:
  # Core infrastructure
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  
  # Database and cache
  - postgres.yaml
  - redis.yaml
  
  # Application
  - app-deployment.yaml
  
  # Networking
  - ingress.yaml
  
  # Monitoring
  - monitoring.yaml

commonLabels:
  app: ai-bi-system
  environment: production
  managed-by: terraform

commonAnnotations:
  description: "AI Business Intelligence System"
  version: "1.0.0"

images:
  - name: ai-business-intelligence
    newTag: latest
    newName: ai-business-intelligence

configMapGenerator:
  - name: ai-bi-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO

secretGenerator:
  - name: ai-bi-secrets
    behavior: merge
    literals:
      - DB_PASSWORD=change-me-in-production
      - JWT_SECRET=change-me-in-production
      - GRAFANA_PASSWORD=change-me-in-production

patches:
  - target:
      kind: Deployment
      name: ai-bi-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"

  - target:
      kind: HorizontalPodAutoscaler
      name: ai-bi-app-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 20

namespace: ai-business-intelligence 