apiVersion: v1
kind: Namespace
metadata:
  name: ai-business-intelligence
  labels:
    name: ai-business-intelligence
    app: ai-bi-system
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-bi-resource-quota
  namespace: ai-business-intelligence
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20" 