apiVersion: v1
kind: Secret
metadata:
  name: ai-bi-secrets
  namespace: ai-business-intelligence
  labels:
    app: ai-bi-system
type: Opaque
data:
  # Database
  DB_PASSWORD: <base64-encoded-db-password>
  
  # JWT
  JWT_SECRET: <base64-encoded-jwt-secret>
  
  # External APIs
  ALPHA_VANTAGE_API_KEY: <base64-encoded-alpha-vantage-key>
  FINNHUB_API_KEY: <base64-encoded-finnhub-key>
  OPENAI_API_KEY: <base64-encoded-openai-key>
  
  # SMTP
  SMTP_HOST: <base64-encoded-smtp-host>
  SMTP_PORT: <base64-encoded-smtp-port>
  SMTP_USERNAME: <base64-encoded-smtp-username>
  SMTP_PASSWORD: <base64-encoded-smtp-password>
  
  # Webhooks
  WEBHOOK_URL: <base64-encoded-webhook-url>
  WEBHOOK_SECRET: <base64-encoded-webhook-secret>
  
  # SSL/TLS Certificates (if using custom certs)
  SSL_CERT: <base64-encoded-ssl-cert>
  SSL_KEY: <base64-encoded-ssl-key>
  
  # Monitoring
  SENTRY_DSN: <base64-encoded-sentry-dsn>
  PROMETHEUS_TOKEN: <base64-encoded-prometheus-token> 